FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install -g firebase-tools
RUN firebase init

COPY . .

ARG FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_STORAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDER_ID
ARG FIREBASE_APP_ID
ARG FIREBASE_MEASUREMENT_ID

ENV FIREBASE_API_KEY=$FIREBASE_API_KEY
ENV FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
ENV FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
ENV FIREBASE_APP_ID=$FIREBASE_APP_ID
ENV FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID

# Add a step to verify environment variables
RUN echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" && \
    echo "FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" && \
    echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID"

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist/brmo/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
